In [1]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from imutils import paths
import matplotlib.pyplot as plt
import numpy as np
import os


In [49]:
learning_rate = 1e-4
Epochs = 23
Batch_size = 30

In [7]:
dataset = r"E:\maskdetection\train"
types = ['Mask','Non Mask']

In [8]:
print("Loading images---")

Loading images---


In [9]:
data = []
labels = []

In [10]:
for category in types:
    path = os.path.join(dataset, category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        image = load_img(img_path, target_size=(224,224))
        image = img_to_array(image)
        image = preprocess_input(image)
        data.append(image)
        labels.append(category)

In [11]:
lb = LabelBinarizer()
labels = lb.fit_transform(labels)
labels = to_categorical(labels)

In [12]:
data = np.array(data, dtype='float32')
labels = np.array(labels)

In [23]:
(train_x, test_x, train_y, test_y) = train_test_split(data, labels, test_size = 0.18, stratify = labels, random_state = 40
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     
                                                     )

In [24]:
print(data)

[[[[ 1.          0.9137255   0.7411765 ]
   [ 1.          0.92156863  0.78039217]
   [ 1.          0.90588236  0.79607844]
   ...
   [-0.23137254 -0.23921567 -0.25490195]
   [-0.17647058 -0.19215685 -0.18431371]
   [-0.20784312 -0.19999999 -0.23921567]]

  [[ 1.          0.9137255   0.75686276]
   [ 1.          0.9137255   0.7411765 ]
   [ 1.          0.92156863  0.7254902 ]
   ...
   [-0.1607843  -0.16862744 -0.19999999]
   [-0.17647058 -0.19999999 -0.23921567]
   [-0.19215685 -0.19999999 -0.23921567]]

  [[ 1.          0.9137255   0.75686276]
   [ 1.          0.92156863  0.7647059 ]
   [ 0.9843137   0.92156863  0.77254903]
   ...
   [-0.16862744 -0.17647058 -0.19215685]
   [-0.19999999 -0.20784312 -0.23921567]
   [-0.16862744 -0.17647058 -0.20784312]]

  ...

  [[ 0.20784318  0.20784318  0.19215691]
   [ 0.18431377  0.19215691  0.15294123]
   [ 0.1686275   0.17647064  0.13725495]
   ...
   [-0.8039216  -0.84313726 -0.8117647 ]
   [-0.84313726 -0.85882354 -0.8509804 ]
   [-0.81960785 

In [25]:
#the training image generator for data augumentation

In [26]:
augument = ImageDataGenerator( rotation_range = 20, zoom_range=0.15, width_shift_range=0.2, height_shift_range=0.2, shear_range=0.15,
                         horizontal_flip=True, fill_mode='nearest'
)

In [27]:
print("loading the MobileNetV2")

loading the MobileNetV2


In [28]:
ground = MobileNetV2(weights='imagenet', include_top=False, input_tensor = Input(shape=(224, 224,3)))

In [29]:
MainModel = ground.output

In [38]:
MainModel = AveragePooling2D(pool_size = (5, 5))(MainModel)
MainModel = Flatten(name= 'flatten')(MainModel)
MainModel = Dense(128, activation = 'relu')(MainModel)
MainModel = Dropout(0.5)(MainModel)
MainModel = Dense(2, activation='softmax')(MainModel)

ValueError: Input 0 of layer average_pooling2d_6 is incompatible with the layer: expected ndim=4, found ndim=2. Full shape received: (None, 2)

In [40]:
model = Model(inputs=ground.input,outputs=MainModel)

In [56]:
for layer in ground.layers:
    layer.trainable = False
    

In [57]:
#compliling the model
print("Compiling model")
opt = Adam(lr= learning_rate, decay= learning_rate / Epochs)
model.compile(loss = 'binary_crossentropy', optimizer = opt, metrics = ['accuracy'])

Compiling model


In [55]:
#train the head of the network
H = model.fit(augument.flow(train_x, train_y, batch_size=BS), steps_per_epoch = len(train_x) // Batch_size, 
              validation_data = (train_x, train_y),
              validation_steps = len(test_x) // Batch_size,
              epochs = Epochs
             )

Epoch 1/23
16/16 [==============================] - 79s 5s/step - loss: 0.8572 - accuracy: 0.5063 - val_loss: 0.6085 - val_accuracy: 0.7927
Epoch 2/23
16/16 [==============================] - 48s 3s/step - loss: 0.6128 - accuracy: 0.7511 - val_loss: 0.4394 - val_accuracy: 0.9472
Epoch 3/23
16/16 [==============================] - 47s 3s/step - loss: 0.4611 - accuracy: 0.8723 - val_loss: 0.3295 - val_accuracy: 0.9675
Epoch 4/23
16/16 [==============================] - 39s 2s/step - loss: 0.3856 - accuracy: 0.9069 - val_loss: 0.2532 - val_accuracy: 0.9736
Epoch 5/23
16/16 [==============================] - 36s 2s/step - loss: 0.2655 - accuracy: 0.9697 - val_loss: 0.1961 - val_accuracy: 0.9817
Epoch 6/23
16/16 [==============================] - 36s 2s/step - loss: 0.2424 - accuracy: 0.9654 - val_loss: 0.1570 - val_accuracy: 0.9878
Epoch 7/23
16/16 [==============================] - 43s 3s/step - loss: 0.2246 - accuracy: 0.9567 - val_loss: 0.1288 - val_accuracy: 0.9898
Epoch 8/23
16/16 [==

In [58]:
print("evaluating the trained CNN")

evaluating the trained CNN


In [74]:
prediction = model.predict(test_x, batch_size = BS)
# for every image in the training set we need to find the index of the label with the corresponding largest predicted probability

In [75]:
prediction = np.argmax(prediction, axis = 1)

In [76]:
#display the cassification report
print(classification_report(test_y.argmax(axis = 1), prediction, target_names = lb.classes_))

              precision    recall  f1-score   support

        Mask       1.00      0.98      0.99        54
    Non Mask       0.98      1.00      0.99        54

    accuracy                           0.99       108
   macro avg       0.99      0.99      0.99       108
weighted avg       0.99      0.99      0.99       108



In [79]:
#saving the model
print('saving model.....')
model.save('face_mask_detector.model', save_format = 'h5')

saving model.....
